### ISSUE TITLE
Building errors

### ISSUE THREAD

**Issue by moh1122** [Bizzi-Body/SYNCANO-COLLECTIONVIEW-DATA-UPLOAD-IMAGES-START#1]
Hello 
Great app
But when im running pod install im getting errors:
Unable to satisfy the following requirements:

- `syncano-ios` required by `Podfile`
- `syncano-ios (= 4.1.1)` required by `Podfile.lock`

any clue?

**Comment by moh1122** [comment]
fixed it 
sorry for tht

**Comment by Bizzi-Body** [comment]
I just saw your issue - what was the solution?  (Glad you resolved the problem)

**Comment by moh1122** [comment]
Thnk u 4 your reply
i fixed the " in pods btw they are correct but i opened the file in textedit

**Comment by Bizzi-Body** [comment]
Ah ha.
